export {MainTemplate} from './MainTemplate'
export {LoginTemplate} from './LoginTemplate'
export {RegisterTemplate} from './RegisterTemplate'
export {WriteTemplate} from './WriteTemplate'
export {DetailTemplate} from './DetailTemplate'