
export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const GET_INFO = "GET_INFO"
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS"
export const GET_INFO_FAILURE = "GET_INFO_FAILURE"

export const POST = "POST"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAILURE = "POST_FAILURE"

export const GET_POST = "GET_POST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAILURE"

export const GET_DETAIL = "GET_DETAIL"
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS"
export const GET_DETAIL_FAILURE = "GET_DETAIL_FAILURE"

export const COMMENT = "COMMENT"
export const COMMENT_SUCCESS = "COMMENT_SUCCESS"
export const COMMENT_FAILURE = "COMMENT_FAILURE"

export const GET_COMMENT = "GET_COMMENT"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE"

export const GET_BY_TIME = "GET_BY_TIME"
export const GET_BY_TIME_SUCCESS = "GET_BY_TIME_SUCCESS"
export const GET_BY_TIME_FAILURE = "GET_BY_TIME_FAILURE"

export const GET_STATICS = "GET_STATICS"
export const GET_STATICS_SUCCESS = "GET_STATICS_SUCCESS"
export const GET_STATICS_FAILURE = "GET_STATICS_FAILURE"